"use client";

import Link from "next/link";
import { useAuth } from "@/hooks/auth";
import { usePathname } from "next/navigation";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyMediaList",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={`${inter.className} bg-gray-800 w-full`}>
      <ProfileHeader />
      <main className="p-3">{children}</main>
    </main>
  );
}

interface NavItemProps {
  children: React.ReactNode;
  href: string;
}

function NavItem({ children, href }: NavItemProps) {
  const pathname = usePathname();
  const { profile } = useAuth();
  const ref = `/profile/${profile?.username}/${href}`;

  if (pathname === ref) {
    return (
      <Link className={`transition-colors text-primary-500`} href={ref}>
        <span className="">{children}</span>
      </Link>
    );
  }

  return (
    <Link className={`transition-colors hover:text-primary-500`} href={ref}>
      <span>{children}</span>
    </Link>
  );
}

function ProfileHeader() {
  const { profile } = useAuth();

  return (
    <div className="w-full flex flex-col ">
      <section className="w-full h-28 bg-gray-900"></section>
      <div className="w-full font-medium p-3 bg-gray-900 relative shadow-md">
        <Image
          className=" rounded-full drop-shadow-md absolute -bottom-7 left-5"
          src={profile?.avatar_url || ""}
          alt=""
          width={100}
          height={100}
        />
        <nav className=" flex gap-5 ml-32 font-medium bg-gray-900">
          <NavItem href="watchlist">Watchlist</NavItem>
          <NavItem href="readlist">Readlist</NavItem>
          <NavItem href="rankings">Rankings</NavItem>
        </nav>
      </div>
    </div>
  );
}
